### ISSUE TITLE
Dome Slaving persistent? (please)

### ISSUE THREAD

**Issue by Bruceaust** [ASCOMInitiative/ASCOMDeviceHub#16] opened 2024-03-12 01:35 UTC
I have an issue with dome slaving in device hub. All works well for me _except_..... when connecting my device hub dome from within NINA, the "slave dome" setting in device hub is not a setting that remains after shut down. This means i can connect to the dome OK every time .... but each time I have to reopen Device hub and check the "slave dome" box in order to get my dome to slave/track the OTA. it would be really nice (for me!) if that slave dome check box could be made to a perminent configuration of my system. ....ie hit the connect equipment and everything connects and works without having to go back into Device Hub to turn on slaving.

Perhaps the slaving could be part of the initial dome setup?

Regards,
Bruce

**Comment by astroman133** [comment] 2024-03-12 01:46
The correct way to ask a question about the ASCOM Platform and the drivers and simulators that it contains is to post the question on the ASCOM-Talk forum on groups.io. This is the correct place to register an issue with Device Hub.

In answer to your isssue please read the following:

The Slaved To Telescope setting is not and cannot be persistent. This means that it cannot remain after shutdown. In order for it to work, Device Hub must be connected to a Telescope and a Dome. There are also some users for whom on-connect slaving would not be a desired behavior. For example, they may want the shutter to be opened and the telescope slewed away from its park position before slaving the dome to the scope via Device Hub.

If an application, like NINA, sets the Device Hub Dome driver's Slaved property to True, this should be almost immediately reflected in the Slaved To Telescope checkbox in the Device Hub user interface. However, there are several additional prerequisites that must be satisfied in order for this to happen.

When an application attempts to set Slaved to True additional capabilities and statuses are checked to determine if the dome and telescope are in a state that supports slaving. Below are the additional prerequisites:

The underlying Dome driver must support the ability to rotate the dome by setting the Azimuth property.  Device Hub must be able to read the Telescope Status Properties and a telescope must be Connected. The underlying Telescope driver's RightAscension, Altitude, and Azimuth must have been read and must be reasonable values. The underlying Telescope driver's SiteElevation, SiteLatitude, and SiteLongitude properties must have been accurately set. Telescope slewing must support the J2000 or JNOW coordinate systems.

If the above conditions are met and the Dome driver's Slaved property has been set to True by either a connected application or through the DH user interface then the SlavedToTelescope checkbox will be checked, as requested, and DH will attempt to slew the dome to a position that places the slit over the telescope. Additional data, such as the X, Y, and Z distance from the center of the dome to the telescope will be used to calculate a dome azimuth, and optionally altitude and an attempt will be made to move it there, if any movement is required. If DH gets this far then the Dome Command Activity Log will show what is occurring.

Before replying to your query I wrote a simple test program to verify that DH is operating as designed. The above behavior is what I observed. DH should also report back to the application why setting the Slaved property failed. It is up to the application how that failure is reported back to the user.

If you have believe that the prerequisite settings are correctly set and are still unable to set the Dome's Slaved property from an application,  but you can set it manually via the SlavedToTelescope checkbox in the DH user interface, then I would suggest that the application that you are using may be having a problem. You should contact them for support.

I am closing this issue because 1) persisting the Slaving switch will cause issues with users and is not implemented, by design and 2) this is already the design behavior. If all the prerequisite criteria are met, setting the DH dome driver's slaved property will cause the Slaved checkbox on the Dome Motion screen to be checked and will initiate slaved slewing.

**Closed as completed by astroman133** 2024-03-12 01:46 UTC
